# Generated by Django 4.0.6 on 2022-07-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['game', 'name']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['display_name']},
        ),
        migrations.AlterModelOptions(
            name='submition',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='submition',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='submition',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('v', 'Verified'), ('d', 'Denied')], default='p', help_text='Submition Status', max_length=1),
        ),
    ]
