# Generated by Django 4.0.6 on 2022-07-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_alter_category_options_alter_game_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submition',
            name='game',
        ),
        migrations.AddField(
            model_name='submition',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='leaderboard.category'),
            preserve_default=False,
        ),
    ]
