# Generated by Django 4.0.6 on 2022-07-31 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_remove_submition_game_submition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='submition',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifier', to='leaderboard.player'),
        ),
        migrations.AlterField(
            model_name='submition',
            name='video_link',
            field=models.URLField(max_length=500),
        ),
    ]
